SELECT CURRENT SERVER FROM SYSIBM.SYSDUMMY1;

SELECT CURRENT SERVER
      ,DBNAME
      ,SUBSTR(CREATOR,1,8)        AS CREATOR
      ,SUBSTR(NAME,1,18)          AS NAME
  FROM SYSIBM.SYSTABLES
 WHERE CREATOR = 'DEV001'
   AND NAME    = 'ORDERLINES' ;   

SELECT CURRENT SERVER
      ,COLNO
      ,SUBSTR(name,1,15)            AS COLNAME
  FROM SYSIBM.SYSCOLUMNS
 WHERE TBCREATOR = 'DEV001'
   AND TBNAME    = 'ORDERLINES' 
 ORDER BY COLNO;                  