-- DO NOT DELETE 3 FOLLOWING LINES
-- DATA FILE: MICTO01.TEST.DATA
-- DESCRIPTION: 
-- TIMESTAMP: Thu, 19 May 2022 09:53:46 GMT
 FASTLOAD   INDDN SYSULD
  INPUT-FORMAT UNLOAD
  SET-COPYPENDING NO
  SET-CHECKPENDING NO
  OUTPUT-CONTROL BUILD
  RESUME YES                           LOG NO  ENFORCE NO
  ESTIMATED-INPUT              300
  EBCDIC  CCSID(1047)
  INTO TABLE  DEVOPSWS.TEST_CASES_ORDERLINES
                                   IGNOREFIELDS YES
               OBID      3
